name: Java CI with Maven and Release

on:
  push:
    tags:
      - 'v*' # Triggers the workflow on version tags like v1.0, v2.1.1, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create releases and upload assets

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21 
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin' # You can choose other distributions like 'adopt', 'zulu'
        cache: 'maven'

    - name: Build with Maven
      # This command cleans, builds, and packages your project.
      # The -B flag runs Maven in non-interactive (batch) mode.
      run: mvn -B clean package --file pom.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: mikechao/jdbc-explorer

    - name: Create Release with Assets
      uses: softprops/action-gh-release@v2.2.2
      with:
        name: Release ${{ github.ref_name }}
        # You can use glob patterns directly
        files: |
          target/*.jar
          !target/*-sources.jar
          !target/*-javadoc.jar
        draft: false
        prerelease: false
        # Optional: auto-generate release notes from PRs and commits
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}